package com.duntale.zsquad.camera;

import com.hypixel.hytale.component.Ref;
import com.hypixel.hytale.component.Store;
import com.hypixel.hytale.logger.HytaleLogger;
import com.hypixel.hytale.math.util.ChunkUtil;
import com.hypixel.hytale.math.vector.Vector3d;
import com.hypixel.hytale.math.vector.Vector3i;
import com.hypixel.hytale.server.core.asset.type.blocktype.config.BlockType;
import com.hypixel.hytale.server.core.modules.entity.component.TransformComponent;
import com.hypixel.hytale.server.core.universe.PlayerRef;
import com.hypixel.hytale.server.core.universe.Universe;
import com.hypixel.hytale.server.core.universe.world.World;
import com.hypixel.hytale.server.core.universe.world.chunk.WorldChunk;
import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;

import javax.annotation.Nonnull;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;

/**
 * Removes <b>structural wall/ceiling blocks</b> between the camera and the
 * player so the player is visible in overhead camera modes.
 *
 * <h3>Algorithm — 2D Floor-Plane Raycast</h3>
 * <ol>
 *   <li>Project the camera direction onto the XZ plane to obtain the 2D cast
 *       direction (from the player toward the camera).</li>
 *   <li>Build up to 9 start positions: the player's tile plus up to 8
 *       adjacent open tiles.</li>
 *   <li>For each start position, perform a <b>2D DDA voxel traversal</b>
 *       (Amanatides–Woo) along the cast direction.</li>
 *   <li>Every visited tile is checked at {@code playerY} (foot level). If
 *       the block is in the {@link #WALL_BLOCK_KEYS} whitelist, the entire
 *       column from {@code playerY} to {@code playerY + WALL_CLEAR_HEIGHT}
 *       is marked for clearing.</li>
 *   <li>Previously cleared blocks that no longer appear in any ray path are
 *       restored.</li>
 * </ol>
 *
 * <p>Because dungeon walls are uniform vertical columns, sampling at one Y
 * level and clearing the full column is both simpler and more robust than
 * 3D ray casting.</p>
 *
 * <p><b>Warning:</b> This modifies actual world state visible to all players.
 * A production solution would need per-player fake block sending.</p>
 */
public class BlockOcclusionManager {

    private static final HytaleLogger LOGGER = HytaleLogger.forEnclosingClass();

    // ── Configuration ────────────────────────────────────────────────────

    /** How many blocks above playerY to clear when a wall column is hit. */
    private static final int WALL_CLEAR_HEIGHT = 4;

    /**
     * Maximum 2D cast distance in blocks. Should exceed the camera's
     * horizontal offset so we reach the camera plane from the player.
     */
    private static final int MAX_CAST_DISTANCE = 20;

    /** Block ID for air — used to detect already-empty positions. */
    private static final int AIR_BLOCK_ID = 0;

    /** Asset key for the built-in barrier block (solid but invisible). */
    private static final String TRANSPARENT_BLOCK_KEY = "Barrier";

    /** Tick interval in ms. */
    private static final long TICK_INTERVAL_MS = 500;

    /**
     * XZ offsets for the 8 adjacent tiles around the player (N, NE, E, SE, S, SW, W, NW).
     */
    private static final int[][] ADJACENT_OFFSETS = {
            { 0, -1}, { 1, -1}, { 1,  0}, { 1,  1},
            { 0,  1}, {-1,  1}, {-1,  0}, {-1, -1}
    };

    /**
     * Structural block asset keys extracted from dungeon-gen themes.
     * Only these blocks are candidates for occlusion removal.
     * Generated by: {@code python3 scripts/extract_wall_blocks.py}
     *
     * <p>Includes: PrimaryWall, SecondaryWall, Ceiling, PillarBase,
     * PillarMiddle, DecayVariants, Stairs, Slab, AccentBlock.</p>
     *
     * <p>Excludes: Floor (below player), OvergrowthBlocks (thin/transparent),
     * RubbleBlocks (floor-level), Fluids, Lights, Props.</p>
     */
    private static final Set<String> WALL_BLOCK_KEYS = Set.of(
            "Deco_Hive",
            "Ore_Gold_Volcanic",
            "Ore_Iron_Stone",
            "Plant_Crop_Mushroom_Block_Blue_Trunk",
            "Plant_Crop_Mushroom_Glowing_Blue",
            "Plant_Moss_Block_Blue",
            "Plant_Moss_Block_Green",
            "Plant_Moss_Block_Green_Dark",
            "Plant_Moss_Block_Red",
            "Plant_Moss_Block_Yellow",
            "Rock_Basalt_Brick",
            "Rock_Basalt_Brick_Pillar_Base",
            "Rock_Basalt_Brick_Pillar_Middle",
            "Rock_Runic_Blue_Brick",
            "Rock_Runic_Blue_Brick_Pillar_Base",
            "Rock_Runic_Blue_Brick_Pipe_Short",
            "Rock_Runic_Brick",
            "Rock_Runic_Cobble_Pillar_Middle",
            "Rock_Runic_Dark_Brick",
            "Rock_Runic_Teal_Brick",
            "Rock_Shale_Brick",
            "Rock_Shale_Cobble",
            "Rock_Slate",
            "Rock_Stone",
            "Rock_Stone_Brick",
            "Rock_Stone_Brick_Half",
            "Rock_Stone_Brick_Mossy",
            "Rock_Stone_Brick_Pillar_Base",
            "Rock_Stone_Brick_Pillar_Middle",
            "Rock_Stone_Brick_Stairs",
            "Rock_Stone_Cobble",
            "Rock_Stone_Cobble_Mossy",
            "Rock_Stone_Mossy",
            "Rock_Volcanic_Brick",
            "Rock_Volcanic_Brick_Pillar_Base",
            "Rock_Volcanic_Brick_Pillar_Middle",
            "Rock_Volcanic_Cobble",
            "Rock_Volcanic_Cracked_Incandescent",
            "Rock_Volcanic_Cracked_Lava",
            "Soil_Gravel_Mossy",
            "Soil_Hive_Brick",
            "Soil_Hive_Brick_Beam",
            "Soil_Hive_Brick_Smooth",
            "Soil_Hive_Corrupted",
            "Soil_Hive_Corrupted_Brick",
            "Wood_Darkwood_Beam",
            "Wood_Darkwood_Planks"
    );

    // ── Camera parameters per player ─────────────────────────────────────

    /**
     * Camera parameters per player: [0] = yaw, [1] = pitch, [2] = distance.
     */
    private final Map<UUID, float[]> playerCameraParams = new ConcurrentHashMap<>();

    // ── State ────────────────────────────────────────────────────────────

    /** Resolved block ID for the transparent occluder block (lazy-init). */
    private int transparentBlockId = -1;

    /** Resolved wall block IDs (lazy-init from WALL_BLOCK_KEYS). */
    private Set<Integer> wallBlockIds = null;

    /** Per-player original block state tracking for restoration. */
    private final Map<UUID, Map<Vector3i, Integer>> playerOriginalBlocks = new ConcurrentHashMap<>();

    /** Tracks which players have occlusion removal enabled. */
    private final Set<UUID> enabledPlayers = ConcurrentHashMap.newKeySet();

    private final ScheduledExecutorService scheduler;
    private ScheduledFuture<?> tickFuture;

    // ── Lifecycle ────────────────────────────────────────────────────────

    /**
     * Creates a new BlockOcclusionManager with a periodic tick loop.
     */
    public BlockOcclusionManager() {
        this.scheduler = Executors.newSingleThreadScheduledExecutor(r -> {
            Thread t = new Thread(r, "BOM-Tick");
            t.setDaemon(true);
            return t;
        });
        this.tickFuture = scheduler.scheduleAtFixedRate(
                this::tick, TICK_INTERVAL_MS, TICK_INTERVAL_MS, TimeUnit.MILLISECONDS
        );
    }

    /**
     * Enables occlusion removal for a player.
     *
     * @param uuid           the player's UUID
     * @param cameraYaw      camera yaw in radians (0=north, PI/2=east, etc.)
     * @param cameraPitch    camera pitch in radians (negative = looking down)
     * @param cameraDistance  camera distance from the player in blocks
     */
    public void enable(@Nonnull UUID uuid, float cameraYaw, float cameraPitch, float cameraDistance) {
        enabledPlayers.add(uuid);
        playerOriginalBlocks.putIfAbsent(uuid, new HashMap<>());
        playerCameraParams.put(uuid, new float[]{cameraYaw, cameraPitch, cameraDistance});
    }

    /**
     * Disables occlusion removal and restores all original blocks.
     *
     * @param uuid  the player's UUID
     * @param world the world to restore blocks in
     */
    public void disable(@Nonnull UUID uuid, @Nonnull World world) {
        enabledPlayers.remove(uuid);
        restoreAllBlocks(uuid, world);
        playerOriginalBlocks.remove(uuid);
        playerCameraParams.remove(uuid);
    }

    /**
     * Checks if occlusion removal is enabled for a player.
     *
     * @param uuid the player's UUID
     * @return true if enabled
     */
    public boolean isEnabled(@Nonnull UUID uuid) {
        return enabledPlayers.contains(uuid);
    }

    /**
     * Shuts down the tick loop and restores all blocks for all players.
     *
     * @param world the world to restore blocks in
     */
    public void shutdown(@Nonnull World world) {
        if (this.tickFuture != null) {
            this.tickFuture.cancel(false);
        }
        this.scheduler.shutdownNow();
        for (UUID uuid : enabledPlayers) {
            restoreAllBlocks(uuid, world);
        }
        enabledPlayers.clear();
        playerOriginalBlocks.clear();
        playerCameraParams.clear();
    }

    // ── Tick Loop ────────────────────────────────────────────────────────

    private void tick() {
        if (enabledPlayers.isEmpty()) return;

        for (UUID uuid : enabledPlayers) {
            PlayerRef playerRef = Universe.get().getPlayer(uuid);
            if (playerRef == null) continue;

            Ref<EntityStore> ref = playerRef.getReference();
            if (ref == null || !ref.isValid()) continue;

            Store<EntityStore> store = ref.getStore();
            World world = store.getExternalData().getWorld();

            world.execute(() -> {
                if (!ref.isValid()) return;
                update(ref, store, world);
            });
        }
    }

    // ── Lazy-init helpers ────────────────────────────────────────────────

    /**
     * Resolves the transparent occluder block ID from the asset map on first use.
     */
    private int getTransparentBlockId() {
        if (transparentBlockId == -1) {
            transparentBlockId = BlockType.getAssetMap().getIndex(TRANSPARENT_BLOCK_KEY);
            LOGGER.atInfo().log("Resolved transparent occluder block ID: {}", transparentBlockId);
        }
        return transparentBlockId;
    }

    /**
     * Resolves the wall block IDs from the asset map on first use.
     * Only these block IDs are eligible for occlusion removal.
     */
    @Nonnull
    private Set<Integer> getWallBlockIds() {
        if (wallBlockIds == null) {
            Set<Integer> ids = new HashSet<>();
            for (String key : WALL_BLOCK_KEYS) {
                int id = BlockType.getAssetMap().getIndex(key);
                if (id > 0) {
                    ids.add(id);
                } else {
                    LOGGER.atWarning().log("Wall block key not found in asset map: {}", key);
                }
            }
            wallBlockIds = ids;
            LOGGER.atInfo().log("Resolved {} wall block IDs for occlusion filtering", ids.size());
        }
        return wallBlockIds;
    }

    // ── Core 2D floor-plane raycast ─────────────────────────────────────

    private void update(@Nonnull Ref<EntityStore> ref,
                        @Nonnull Store<EntityStore> store,
                        @Nonnull World world) {
        PlayerRef playerRef = store.getComponent(ref, PlayerRef.getComponentType());
        if (playerRef == null) return;

        UUID uuid = playerRef.getUuid();
        if (!isEnabled(uuid)) return;

        float[] camParams = playerCameraParams.get(uuid);
        if (camParams == null) return;

        TransformComponent transform = store.getComponent(ref, TransformComponent.getComponentType());
        if (transform == null) return;

        Vector3d playerPos = transform.getPosition();
        int playerX = (int) Math.floor(playerPos.x);
        int playerY = (int) Math.floor(playerPos.y);
        int playerZ = (int) Math.floor(playerPos.z);

        Set<Integer> wallIds = getWallBlockIds();

        // 2D camera direction on XZ plane (player → camera)
        float yaw = camParams[0];
        double dirX = Math.sin(yaw);
        double dirZ = Math.cos(yaw);

        // If top-down (pitch ≈ -PI/2), horizontal direction is near-zero.
        // Use a small fallback to still clear the column above the player.
        double dirLen = Math.sqrt(dirX * dirX + dirZ * dirZ);
        if (dirLen < 0.001) {
            dirX = 0;
            dirZ = 1;
            dirLen = 1;
        }
        double ndx = dirX / dirLen;
        double ndz = dirZ / dirLen;

        int replaceId = getTransparentBlockId();

        // Build start positions: player tile (always) + up to 8 open adjacent
        int[][] startTiles = buildStartTiles(world, wallIds, replaceId, playerX, playerY, playerZ);

        Map<Vector3i, Integer> originalBlocks = playerOriginalBlocks.computeIfAbsent(uuid, k -> new HashMap<>());
        Set<Vector3i> previousPositions = new HashSet<>(originalBlocks.keySet());
        Set<Vector3i> newPositions = new HashSet<>();

        // Cast each 2D ray and collect wall columns to clear
        for (int rayIndex = 0; rayIndex < startTiles.length; rayIndex++) {
            int[] tile = startTiles[rayIndex];
            if (tile == null) continue;

            castRay2D(world, tile[0], tile[1], ndx, ndz, playerY, wallIds, replaceId, newPositions);
        }

        // Restore blocks no longer in any ray path
        for (Vector3i pos : previousPositions) {
            if (!newPositions.contains(pos)) {
                Integer originalBlockId = originalBlocks.remove(pos);
                if (originalBlockId != null) {
                    setBlock(world, pos.getX(), pos.getY(), pos.getZ(), originalBlockId);
                }
            }
        }

        // Replace wall blocks in the ray paths
        for (Vector3i pos : newPositions) {
            if (!originalBlocks.containsKey(pos)) {
                int currentBlockId = getBlock(world, pos.getX(), pos.getY(), pos.getZ());
                if (currentBlockId != AIR_BLOCK_ID
                        && currentBlockId != replaceId
                        && wallIds.contains(currentBlockId)) {
                    originalBlocks.put(pos, currentBlockId);
                    setBlock(world, pos.getX(), pos.getY(), pos.getZ(), replaceId);
                }
            }
        }
    }

    /**
     * Builds the array of starting tile positions. Index 0 is always the
     * player's tile. Indices 1–8 are adjacent tiles that are {@code null}
     * if they contain a wall block at foot or head height.
     *
     * @param world     the world to check blocks in
     * @param wallIds   the set of structural wall block IDs
     * @param replaceId the barrier block ID (walls we already replaced)
     * @param playerX   player's block X
     * @param playerY   player's block Y (foot level)
     * @param playerZ   player's block Z
     * @return array of {@code [tileX, tileZ]}; null entries = skipped
     */
    @Nonnull
    private static int[][] buildStartTiles(@Nonnull World world,
                                            @Nonnull Set<Integer> wallIds,
                                            int replaceId,
                                            int playerX, int playerY, int playerZ) {
        int[][] tiles = new int[9][];

        tiles[0] = new int[]{playerX, playerZ};

        for (int i = 0; i < ADJACENT_OFFSETS.length; i++) {
            int adjX = playerX + ADJACENT_OFFSETS[i][0];
            int adjZ = playerZ + ADJACENT_OFFSETS[i][1];

            int footBlock = getBlock(world, adjX, playerY, adjZ);
            int headBlock = getBlock(world, adjX, playerY + 1, adjZ);

            boolean footIsWall = wallIds.contains(footBlock) || footBlock == replaceId;
            boolean headIsWall = wallIds.contains(headBlock) || headBlock == replaceId;

            if (!footIsWall && !headIsWall) {
                tiles[i + 1] = new int[]{adjX, adjZ};
            }
        }

        return tiles;
    }

    /**
     * Performs a 2D DDA (Amanatides–Woo) voxel traversal from a start tile
     * along the given direction on the XZ plane. For each tile visited, checks
     * if the block at {@code (x, floorY, z)} is a wall block. If so, the full
     * column from {@code floorY} to {@code floorY + WALL_CLEAR_HEIGHT} is
     * added to the clear set.
     *
     * <p>Treats both wall blocks and barrier blocks (previously cleared walls)
     * as walls to prevent flicker caused by reading our own modifications.</p>
     *
     * @param world     the world to read blocks from
     * @param startX    starting tile X
     * @param startZ    starting tile Z
     * @param ndx       normalized 2D direction X (player → camera)
     * @param ndz       normalized 2D direction Z (player → camera)
     * @param floorY    the Y level to sample for wall detection
     * @param wallIds   set of wall block IDs
     * @param replaceId barrier block ID (already-cleared walls to also treat as walls)
     * @param outBlocks set to add block positions to
     */
    private static void castRay2D(@Nonnull World world,
                                   int startX, int startZ,
                                   double ndx, double ndz,
                                   int floorY,
                                   @Nonnull Set<Integer> wallIds,
                                   int replaceId,
                                   @Nonnull Set<Vector3i> outBlocks) {
        // Ray origin: center of starting tile
        double originX = startX + 0.5;
        double originZ = startZ + 0.5;

        int gridX = startX;
        int gridZ = startZ;

        // DDA step direction
        int stepX = (ndx >= 0) ? 1 : -1;
        int stepZ = (ndz >= 0) ? 1 : -1;

        // Distance along ray between consecutive X / Z grid lines
        double tDeltaX = (ndx != 0) ? Math.abs(1.0 / ndx) : Double.MAX_VALUE;
        double tDeltaZ = (ndz != 0) ? Math.abs(1.0 / ndz) : Double.MAX_VALUE;

        // Distance from origin to the first X / Z grid boundary in the ray direction
        double tMaxX = (ndx != 0)
                ? ((ndx > 0 ? (gridX + 1 - originX) : (originX - gridX)) / Math.abs(ndx))
                : Double.MAX_VALUE;
        double tMaxZ = (ndz != 0)
                ? ((ndz > 0 ? (gridZ + 1 - originZ) : (originZ - gridZ)) / Math.abs(ndz))
                : Double.MAX_VALUE;

        double traveled = 0;

        while (traveled < MAX_CAST_DISTANCE) {
            // Check if the tile at floor level contains a wall (or an already-cleared wall)
            int blockId = getBlock(world, gridX, floorY, gridZ);
            if (wallIds.contains(blockId) || blockId == replaceId) {
                // Mark the entire column for clearing
                for (int dy = 0; dy <= WALL_CLEAR_HEIGHT; dy++) {
                    outBlocks.add(new Vector3i(gridX, floorY + dy, gridZ));
                }
            }

            // Step to next tile
            if (tMaxX < tMaxZ) {
                gridX += stepX;
                traveled = tMaxX;
                tMaxX += tDeltaX;
            } else {
                gridZ += stepZ;
                traveled = tMaxZ;
                tMaxZ += tDeltaZ;
            }
        }
    }

    // ── Restoration ──────────────────────────────────────────────────────

    private void restoreAllBlocks(@Nonnull UUID uuid, @Nonnull World world) {
        Map<Vector3i, Integer> originalBlocks = playerOriginalBlocks.get(uuid);
        if (originalBlocks == null) return;

        for (Map.Entry<Vector3i, Integer> entry : originalBlocks.entrySet()) {
            Vector3i pos = entry.getKey();
            setBlock(world, pos.getX(), pos.getY(), pos.getZ(), entry.getValue());
        }
        originalBlocks.clear();
    }

    // ── Block access helpers ─────────────────────────────────────────────

    private static int getBlock(@Nonnull World world, int x, int y, int z) {
        WorldChunk chunk = world.getChunk(ChunkUtil.indexChunkFromBlock(x, z));
        if (chunk == null) return AIR_BLOCK_ID;
        return chunk.getBlock(x, y, z);
    }

    private static void setBlock(@Nonnull World world, int x, int y, int z, int blockId) {
        WorldChunk chunk = world.getChunk(ChunkUtil.indexChunkFromBlock(x, z));
        if (chunk != null) {
            chunk.setBlock(x, y, z, blockId);
        }
    }
}
